//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Theme.Default2016.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Theme.Default2016.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40px {
            get {
                object obj = ResourceManager.GetObject("_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * iScroll Lite base on iScroll v4.1.6 ~ Copyright (c) 2011 Matteo Spinelli, http://cubiq.org
        /// * Released under MIT license, http://cubiq.org/license
        /// */
        ///(function(){var t=Math,e=function(m){return m&gt;&gt;0},x=(/webkit/i).test(navigator.appVersion)?&quot;webkit&quot;:(/firefox/i).test(navigator.userAgent)?&quot;Moz&quot;:&quot;opera&quot; in window?&quot;O&quot;:&quot;&quot;,y=(/android/gi).test(navigator.appVersion),j=(/iphone|ipad/gi).test(navigator.appVersion),d=(/playbook/gi).test(navigator.appVersion),o=(/hp-tablet/gi).test(navigator.appVersion),l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adminflare_min {
            get {
                return ResourceManager.GetString("adminflare_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;content:&quot;&quot;;line-height:0}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}body{background-image:url(&quot;../images/body-bg.png&quot;);min-width:1012px;padding:62px 0 0 112px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adminflare_min1 {
            get {
                return ResourceManager.GetString("adminflare_min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;no-js lt-ie9&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Log In - MultiPlug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;vie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;no-js lt-ie9&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Permission Denied - MultiPlug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Log into Mul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Authorisation {
            get {
                return ResourceManager.GetString("Authorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap body_bg {
            get {
                object obj = ResourceManager.GetObject("body_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(a){a(function(){a.support.transition=(function(){var b=(function(){var e=document.createElement(&quot;bootstrap&quot;),d={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;},c;for(c in d){if(e.style[c]!==undefined){return d[c]}}}());return b&amp;&amp;{end:b}})()})}(window.jQuery);!function(d){var c=&apos;[data-dismiss=&quot;alert&quot;]&apos;,b=function(e){d(e).on(&quot;click&quot;,c,this.close)};b.prototype.close=function(j){var i=d(this),g=i.attr(&quot;data-ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio,canvas,video{display:inline-block;*display:inline;*zoom:1}audio:not([controls]){display:none}html{font-size:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}a:focus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px}a:hover,a:active{outline:0}sub,sup{position:relative;font-size:75%;line-height:0;vertical-align:baseline}sup{top:-0.5em}sub{bottom:-0.25em}img{max-width:10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min_css {
            get {
                return ResourceManager.GetString("bootstrap_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap British_Systems_Logo {
            get {
                object obj = ResourceManager.GetObject("British_Systems_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap British_Systems_Logo_Fade {
            get {
                object obj = ResourceManager.GetObject("British_Systems_Logo_Fade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.btn-deploy&quot;).click(function (event) {
        ///    event.preventDefault();
        ///
        ///    var theRow = $(this).closest(&quot;tr&quot;);
        ///
        ///    $.post($(this).attr(&apos;href&apos;), function (data) {
        ///
        ///    })
        ///    .done(function () {
        ///        $(&apos;.top-right&apos;).notify({
        ///            message: {
        ///                text: &apos;Recipes have been deployed and saved.&apos;
        ///            },
        ///            type: &apos;adminflare&apos;
        ///        }).show()
        ///    });
        ///});.
        /// </summary>
        internal static string deploy_js {
            get {
                return ResourceManager.GetString("deploy_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap evaluation_stamp {
            get {
                object obj = ResourceManager.GetObject("evaluation_stamp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /*  Font Awesome 3.2.1
        /// *  the iconic font designed for Bootstrap
        /// *  ------------------------------------------------------------------------------
        /// *  The full suite of pictographic icons, examples, and documentation can be
        /// *  found at http://fontawesome.io.  Stay up to date on Twitter at
        /// *  http://twitter.com/fontawesome.
        /// *
        /// *  License
        /// *  ------------------------------------------------------------------------------
        /// *  - The Font Awesome font is licensed under SIL OFL 1.1 -
        /// *    http://s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string font_awesome_css {
            get {
                return ResourceManager.GetString("font_awesome_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAwesome_otf {
            get {
                object obj = ResourceManager.GetObject("FontAwesome_otf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_eot {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_svg {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_ttf {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_woff {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* cyrillic-ext */
        ///@font-face {
        ///  font-family: &apos;Open Sans&apos;;
        ///  font-style: italic;
        ///  font-weight: 300;
        ///  font-stretch: 100%;
        ///  src: url(../fonts/memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtE6F15M.woff2) format(&apos;woff2&apos;);
        ///  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
        ///}
        ////* cyrillic */
        ///@font-face {
        ///  font-family: &apos;Open Sans&apos;;
        ///  font-style: italic;
        ///  font-weight: 300;
        ///  font-stretch: 100%;
        ///  src: url(../fonts/memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWvU6F15M.w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fonts {
            get {
                return ResourceManager.GetString("fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///@Include(@Model.Extension.RazorTemplate)
        ///.
        /// </summary>
        internal static string FrameApp {
            get {
                return ResourceManager.GetString("FrameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///@Include(@Model.Extension.RazorTemplate)
        ///.
        /// </summary>
        internal static string FrameExtension {
            get {
                return ResourceManager.GetString("FrameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;span3&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;ul class=&quot;nav nav-list&quot;&gt;
        ///                &lt;li class=&quot;nav-header&quot;&gt;Analytics&lt;/li&gt;
        ///                &lt;li @*class=&quot;active&quot;*@&gt;&lt;a class=&quot;btn-loadlog&quot; data-logtype=&quot;core&quot; data-multiplugapi=&quot;@Raw(Model.Context.Paths.Roots.MultiPlug)diagnostics/logs/system/view&quot; href=&quot;@Raw(Model.Context.Paths.Home)&quot;&gt;MultiPlug.Core&lt;/a&gt;&lt;/li&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeAnalytics {
            get {
                return ResourceManager.GetString("HomeAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using MultiPlug.Base.Http
        ///@model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;div class=&quot;extensions-heading&quot;&gt;
        ///    &lt;h2&gt;Apps&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot; style=&quot;margin-bottom: 20px&quot;&gt;
        ///
        ///        @foreach (var Extension in @Model.MultiPlugAPI.Extensions)
        ///        {
        ///            foreach (var HttpEndpoint in Extension.HttpEndpoints)
        ///            {
        ///                if (HttpEndpoint.isHidden || (HttpEndpoint.Type != HttpEndpointType.App))
        ///                {
        ///                    continue;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeApps {
            get {
                return ResourceManager.GetString("HomeApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///
        ///    &lt;ul class=&quot;nav nav-tabs&quot; id=&quot;myTab&quot;&gt;
        ///        &lt;li class=&quot;active&quot;&gt;&lt;a href=&quot;#events-subs&quot;&gt;Extensions&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;#mappings&quot;&gt;Mappings&lt;/a&gt;&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///    &lt;div id=&quot;myTabContent&quot; class=&quot;tab-content&quot; style=&quot;margin-bottom: 10px&quot;&gt;
        ///        &lt;div class=&quot;tab-pane fade in active&quot; id=&quot;events-subs&quot;&gt;
        ///            &lt;p&gt;Events, Subscriptions and Web Apps of the Extensions&lt;/p&gt;
        ///            &lt;div id=&quot;jstree&quot;&gt;
        ///                &lt;ul&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeExtensions {
            get {
                return ResourceManager.GetString("HomeExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;form class=&quot;&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    @if (Model.Extension.Model.UpdatePending)
        ///    {
        ///        &lt;div class=&quot;alert&quot;&gt;
        ///            &lt;a href=&quot;#&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot;&gt;×&lt;/a&gt;
        ///            &lt;strong&gt;Updates Pending&lt;/strong&gt; Restart the system to apply pending updates.
        ///        &lt;/div&gt;
        ///    }
        ///    &lt;h3 class=&quot;box-header&quot;&gt;Actions&lt;/h3&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeSettings {
            get {
                return ResourceManager.GetString("HomeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Internal Server Error - Multiplug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Internal Server Error&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.6.4 http://jquery.com/ | http://jquery.org/license */
        ///(function(a,b){function cu(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cr(a){if(!cg[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ch||(ch=c.createElement(&quot;iframe&quot;),ch.frameBorder=ch.width=ch.height=0),b.appendChild(ch);if(!ci||!ch.createElement)ci=(ch.contentWindow||ch.contentDocument).document,ci.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_4_min {
            get {
                return ResourceManager.GetString("jquery_1_6_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(n,t,i){function w(t,i){var u,f;if(n.isArray(t)){for(u=t.length-1;u&gt;=0;u--)f=t[u],n.type(f)===&quot;string&quot;&amp;&amp;r.transports[f]||(i.log(&quot;Invalid transport: &quot;+f+&quot;, removing it from the transports list.&quot;),t.splice(u,1));t.length===0&amp;&amp;(i.log(&quot;No transports remain within the specified transport array.&quot;),t=null)}else if(r.transports[t]||t===&quot;auto&quot;){if(t===&quot;auto&quot;&amp;&amp;r._.ieVersion&lt;=8)return[&quot;longPolling&quot;]}else i.log(&quot;Invalid transport: &quot;+t.toString()+&quot;.&quot;),t=null;return t}function b(n){return n===&quot;http:&quot;?80:n===&quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_signalR_2_2_0_min {
            get {
                return ResourceManager.GetString("jquery_signalR_2_2_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jsTree - v3.3.3 - 2016-10-31 - (MIT) */
        ///!function(a){&quot;use strict&quot;;&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):&quot;undefined&quot;!=typeof module&amp;&amp;module.exports?module.exports=a(require(&quot;jquery&quot;)):a(jQuery)}(function(a,b){&quot;use strict&quot;;if(!a.jstree){var c=0,d=!1,e=!1,f=!1,g=[],h=a(&quot;script:last&quot;).attr(&quot;src&quot;),i=window.document;a.jstree={version:&quot;3.3.3&quot;,defaults:{plugins:[]},plugins:{},path:h&amp;&amp;-1!==h.indexOf(&quot;/&quot;)?h.replace(/\/[^\/]+$/,&quot;&quot;):&quot;&quot;,idregex:/[\\:&amp;!^|()\[\]&lt;&gt;@*&apos;+~#&quot;;.,=\- \/${}%?`]/g,root:&quot;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_min {
            get {
                return ResourceManager.GetString("jstree_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-node,.jstree-children,.jstree-container-ul{display:block;margin:0;padding:0;list-style-type:none;list-style-image:none}.jstree-node{white-space:nowrap}.jstree-anchor{display:inline-block;color:#000;white-space:nowrap;padding:0 4px 0 1px;margin:0;vertical-align:top}.jstree-anchor:focus{outline:0}.jstree-anchor,.jstree-anchor:link,.jstree-anchor:visited,.jstree-anchor:hover,.jstree-anchor:active{text-decoration:none;color:inherit}.jstree-icon{display:inline-block;text-decoration:none;margin:0;padding: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_style_min {
            get {
                return ResourceManager.GetString("jstree_style_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@using MultiPlug.Base.Http
        ///@{
        ///    string AppsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.HttpEndpointType.App) ? &quot;active&quot; : &quot;&quot;; ;
        ///    string ExtensionsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.HttpEndpointType.Settings) ? &quot;active&quot; : &quot;&quot;;
        ///    string SettingsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.HttpEndpointType.System) ? &quot;active&quot; : &quot;&quot;;
        ///    string AnalyticsActive = (Model.Context.Paths.Location == MultiPlug [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_menu_bg {
            get {
                object obj = ResourceManager.GetObject("left_menu_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqW106F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqW106F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWt06F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWt06F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtE6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtE6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtk6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtk6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtU6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWtU6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWu06F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWu06F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWuk6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWuk6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWuU6F {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWuU6F", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWvU6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWvU6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWxU6F15M {
            get {
                object obj = ResourceManager.GetObject("memtYaGs126MiZpBA_UFUIcVXSCEkx2cmqvXlWqWxU6F15M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTS_muw {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTS_muw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTS2mu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTS2mu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSCmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSCmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSGmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSGmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSKmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSKmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSOmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSOmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSumu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSumu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSymu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTSymu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTUGmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTUGmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTVOmu1aB {
            get {
                object obj = ResourceManager.GetObject("memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTVOmu1aB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Modernizr 2.6.2 (Custom Build) | MIT &amp; BSD
        /// * Build: http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inline [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modernizr_2_6_2_js {
            get {
                return ResourceManager.GetString("modernizr_2_6_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug {
            get {
                object obj = ResourceManager.GetObject("MultiPlug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Icon {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Login {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function PopulateEventsData(mpevent) {
        ///
        ///    optgroups = [];
        ///
        ///    $.ajax({
        ///        url: &apos;multiplug/events/&apos;,
        ///        type: &apos;GET&apos;,
        ///        error: function () {
        ///            callback();
        ///        },
        ///        success: function (res) {
        ///
        ///            $.each(res.extensions, function () {
        ///                var exname = this.name;
        ///                optgroups.push({
        ///                    name: exname
        ///                });
        ///                $.each(this.events, function () {
        ///                    mpeventids.push({
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multiplug_selectize {
            get {
                return ResourceManager.GetString("multiplug_selectize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Small {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug App Not Found&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundApp {
            get {
                return ResourceManager.GetString("NotFoundApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug Extension Not Found&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundExtension {
            get {
                return ResourceManager.GetString("NotFoundExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section class=&quot;container&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundGlobal {
            get {
                return ResourceManager.GetString("NotFoundGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;content:&quot;&quot;;line-height:0}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}.pages-messages .nav-stacked .badge{display:inline-block;margin-top:1px;font-size:11px}.pages-messages .well{border:none!important;padding:0}.pages-messages .box [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_min {
            get {
                return ResourceManager.GetString("pages_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Select2 4.0.3 | https://github.com/select2/select2/blob/master/LICENSE.md */!function(a){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):a(&quot;object&quot;==typeof exports?require(&quot;jquery&quot;):jQuery)}(function(a){var b=function(){if(a&amp;&amp;a.fn&amp;&amp;a.fn.select2&amp;&amp;a.fn.select2.amd)var b=a.fn.select2.amd;var b;return function(){if(!b||!b.requirejs){b?c=b:b={};var a,c,d;!function(b){function e(a,b){return u.call(a,b)}function f(a,b){var c,d,e,f,g,h,i,j,k,l,m,n=b&amp;&amp;b.split(&quot;/&quot;),o=s.map,p=o&amp;&amp;o[&quot;*&quot;]||{};if(a&amp;&amp;&quot;.&quot;===a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string select2_min {
            get {
                return ResourceManager.GetString("select2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .select2-container{box-sizing:border-box;display:inline-block;margin:0;position:relative;vertical-align:middle}.select2-container .select2-selection--single{box-sizing:border-box;cursor:pointer;display:block;height:28px;user-select:none;-webkit-user-select:none}.select2-container .select2-selection--single .select2-selection__rendered{display:block;padding-left:8px;padding-right:20px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.select2-container .select2-selection--single .select2-selection__c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string select2_min1 {
            get {
                return ResourceManager.GetString("select2_min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * selectize.default.css (v0.12.4) - Default Theme
        /// * Copyright (c) 2013–2015 Brian Reavis &amp; contributors
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this
        /// * file except in compliance with the License. You may obtain a copy of the License at:
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software distributed under
        /// * the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectize_default {
            get {
                return ResourceManager.GetString("selectize_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! selectize.js - v0.12.4 | https://github.com/selectize/selectize.js | Apache License (v2) */
        ///!function(a,b){&quot;function&quot;==typeof define&amp;&amp;define.amd?define(&quot;sifter&quot;,b):&quot;object&quot;==typeof exports?module.exports=b():a.Sifter=b()}(this,function(){var a=function(a,b){this.items=a,this.settings=b||{diacritics:!0}};a.prototype.tokenize=function(a){if(a=e(String(a||&quot;&quot;).toLowerCase()),!a||!a.length)return[];var b,c,d,g,i=[],j=a.split(/ +/);for(b=0,c=j.length;b&lt;c;b++){if(d=f(j[b]),this.settings.diacritics)for(g in h) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectize_min {
            get {
                return ResourceManager.GetString("selectize_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///      display:inline-block;
        ///      vertical-align:middle;
        ///    }
        ///    .setting-heading img {
        ///    opacity: 0.7; filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///    margin-left:0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Add Extensions&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///@if (Model.Extension.Model.UpdatePending)
        ///{
        ///    &lt;div class= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsAdd {
            get {
                return ResourceManager.GetString("SettingsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Apps&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsApps {
            get {
                return ResourceManager.GetString("SettingsApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Environment&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///    &lt;form method=&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsEnvironment {
            get {
                return ResourceManager.GetString("SettingsEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///@functions
        ///{
        ///    string DrawActionButton(string theAssemblyName, bool isEnabled, bool isLoaded)
        ///    {
        ///        if (isLoaded)
        ///        {
        ///            return &quot;&lt;a class=\&quot;btn btn-red btn-loadextension\&quot; id=&quot; + theAssemblyName + &quot;-btnStartStop\&quot; href=\&quot;multiplug/extensions/unload/?extension=&quot; + theAssemblyName + &quot;\&quot;&gt;&lt;i class=\&quot;icon-stop\&quot;&gt;&lt;/i&gt;&lt;/a&gt;&quot;;
        ///        }
        ///        else if (!isLoaded &amp;&amp; isEnabled)
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsExtensions {
            get {
                return ResourceManager.GetString("SettingsExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Hosting&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form style=&quot;display:contents&quot; method=&quot;post&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHosting {
            get {
                return ResourceManager.GetString("SettingsHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Housekeeping&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;h3 class=&quot;box-header&quot;&gt;
        ///    Storage        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHousekeeping {
            get {
                return ResourceManager.GetString("SettingsHousekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;div&gt;
        ///    &lt;h2&gt;Housekeeping&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;span5&quot;&gt;
        ///            &lt;h4&gt;Log Files&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span7&quot;&gt;
        ///            &lt;h4 id=&quot;FileNameHeading&quot;&gt;File:&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;span5&quot;&gt;
        ///            &lt;div id=&quot;jstree&quot;&gt;
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHousekeepingStorage {
            get {
                return ResourceManager.GetString("SettingsHousekeepingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Performance&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsPerformance {
            get {
                return ResourceManager.GetString("SettingsPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .permissions-heading img,
        ///    .permissions-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .permissions-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .permissions-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;permissions-heading&quot;&gt;
        ///    &lt;h2&gt;Permissions&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsPermissions {
            get {
                return ResourceManager.GetString("SettingsPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///@functions
        ///{
        ///    string isEnabled(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;&lt;i class=\&quot;icon-ok\&quot;&gt;&lt;/i&gt;&quot; : &quot;&lt;i class=\&quot;icon-remove\&quot;&gt;&lt;/i&gt;&quot;;
        ///    }
        ///
        ///    string isChecked(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;checked&quot; : string.Empty;
        ///    }
        ///
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsRecipes {
            get {
                return ResourceManager.GetString("SettingsRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .permissions-heading img,
        ///    .permissions-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .permissions-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .permissions-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;permissions-heading&quot;&gt;
        ///    &lt;h2&gt;Security&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsSecurity {
            get {
                return ResourceManager.GetString("SettingsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Environment&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///    &lt;form method=&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsSystem {
            get {
                return ResourceManager.GetString("SettingsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///      display:inline-block;
        ///      vertical-align:middle;
        ///    }
        ///    .setting-heading img {
        ///    opacity: 0.7; filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///    margin-left:0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Update MultiPlug&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form class=&quot;&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsUpdate {
            get {
                return ResourceManager.GetString("SettingsUpdate", resourceCulture);
            }
        }
    }
}
