//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Theme.Default2016.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Theme.Default2016.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40px {
            get {
                object obj = ResourceManager.GetObject("_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _59ZRklaO5bWGqF5A9baEERJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("_59ZRklaO5bWGqF5A9baEERJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(){var a=&quot;assets/css/&quot;+DEMO_ADMINFLARE_VERSION+&quot;/&quot;;$(document).ready(function(){var e=function(k){var l=demoGetColor(DEMO_CURRENT_THEME),i=demoGetColor(k);$(&quot;#styleswitcher-buttons .btn-&quot;+l).text(demoCapitaliseFirstLetter(l));var m=$(&quot;#styleswitcher-buttons .btn-code&quot;);m.next(&quot;br&quot;).remove();m.remove();$(&quot;#styleswitcher-buttons .btn-&quot;+i).text(&quot;Primary&quot;).parent().next().prepend(&apos;&lt;code class=&quot;btn-code&quot;&gt;btn btn-primary&lt;/code&gt;&lt;br&gt;&apos;);var j=$(&quot;#styleswitcher-progress-bars .progress-code&quot;);j.prev(&quot;br&quot;).rem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adminflare_demo_min {
            get {
                return ResourceManager.GetString("adminflare_demo_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * iScroll Lite base on iScroll v4.1.6 ~ Copyright (c) 2011 Matteo Spinelli, http://cubiq.org
        /// * Released under MIT license, http://cubiq.org/license
        /// */
        ///(function(){var t=Math,e=function(m){return m&gt;&gt;0},x=(/webkit/i).test(navigator.appVersion)?&quot;webkit&quot;:(/firefox/i).test(navigator.userAgent)?&quot;Moz&quot;:&quot;opera&quot; in window?&quot;O&quot;:&quot;&quot;,y=(/android/gi).test(navigator.appVersion),j=(/iphone|ipad/gi).test(navigator.appVersion),d=(/playbook/gi).test(navigator.appVersion),o=(/hp-tablet/gi).test(navigator.appVersion),l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adminflare_min {
            get {
                return ResourceManager.GetString("adminflare_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;content:&quot;&quot;;line-height:0}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}body{background-image:url(&quot;../images/body-bg.png&quot;);min-width:1012px;padding:62px 0 0 112px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adminflare_min1 {
            get {
                return ResourceManager.GetString("adminflare_min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;no-js lt-ie9&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;
        ///        MultiPlug - Sign In
        ///    &lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Authorisation {
            get {
                return ResourceManager.GetString("Authorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap body_bg {
            get {
                object obj = ResourceManager.GetObject("body_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(a){a(function(){a.support.transition=(function(){var b=(function(){var e=document.createElement(&quot;bootstrap&quot;),d={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;},c;for(c in d){if(e.style[c]!==undefined){return d[c]}}}());return b&amp;&amp;{end:b}})()})}(window.jQuery);!function(d){var c=&apos;[data-dismiss=&quot;alert&quot;]&apos;,b=function(e){d(e).on(&quot;click&quot;,c,this.close)};b.prototype.close=function(j){var i=d(this),g=i.attr(&quot;data-ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap British_Systems_Logo {
            get {
                object obj = ResourceManager.GetObject("British_Systems_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap British_Systems_Logo_Fade {
            get {
                object obj = ResourceManager.GetObject("British_Systems_Logo_Fade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw {
            get {
                object obj = ResourceManager.GetObject("cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.btn-deploy&quot;).click(function (event) {
        ///    event.preventDefault();
        ///
        ///    var theRow = $(this).closest(&quot;tr&quot;);
        ///
        ///    $.post($(this).attr(&apos;href&apos;), function (data) {
        ///
        ///    })
        ///    .done(function () {
        ///        $(&apos;.top-right&apos;).notify({
        ///            message: {
        ///                text: &apos;Recipes have been deployed and saved.&apos;
        ///            },
        ///            type: &apos;adminflare&apos;
        ///        }).show()
        ///    });
        ///});.
        /// </summary>
        internal static string deploy_js {
            get {
                return ResourceManager.GetString("deploy_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTa_j2U0lmluP9RWlSytm3ho {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTa_j2U0lmluP9RWlSytm3ho", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTaaRobkAwv3vxw3jMhVENGA {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTaaRobkAwv3vxw3jMhVENGA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTegdm0LZdjqr5_oayXSOefg {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTegdm0LZdjqr5_oayXSOefg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTf8zf_FOSsgRmwsS7Aa9k2w {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTf8zf_FOSsgRmwsS7Aa9k2w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTRWV49_lSm1NYrwo_zkhivY {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTRWV49_lSm1NYrwo_zkhivY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTT0LW_43aMEzIO6XUTLjad8 {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTT0LW_43aMEzIO6XUTLjad8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DXI1ORHCpsQm3Vp6mXoaTZX5f_9o1vgP2EXwfjgl7AY {
            get {
                object obj = ResourceManager.GetObject("DXI1ORHCpsQm3Vp6mXoaTZX5f_9o1vgP2EXwfjgl7AY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap evaluation_stamp {
            get {
                object obj = ResourceManager.GetObject("evaluation_stamp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /*  Font Awesome 3.2.1
        /// *  the iconic font designed for Bootstrap
        /// *  ------------------------------------------------------------------------------
        /// *  The full suite of pictographic icons, examples, and documentation can be
        /// *  found at http://fontawesome.io.  Stay up to date on Twitter at
        /// *  http://twitter.com/fontawesome.
        /// *
        /// *  License
        /// *  ------------------------------------------------------------------------------
        /// *  - The Font Awesome font is licensed under SIL OFL 1.1 -
        /// *    http://s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string font_awesome_css {
            get {
                return ResourceManager.GetString("font_awesome_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAwesome_otf {
            get {
                object obj = ResourceManager.GetObject("FontAwesome_otf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_eot {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_svg {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_ttf {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fontawesome_webfont_woff {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* cyrillic-ext */
        ///@font-face {
        ///  font-family: &apos;Open Sans&apos;;
        ///  font-style: italic;
        ///  font-weight: 300;
        ///  src: local(&apos;Open Sans Light Italic&apos;), local(&apos;OpenSans-LightItalic&apos;), url(../fonts/PRmiXeptR36kaC0GEAetxhgVThLs8Y7ETJzDCYFCSLE.woff2) format(&apos;woff2&apos;);
        ///  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
        ///}
        ////* cyrillic */
        ///@font-face {
        ///  font-family: &apos;Open Sans&apos;;
        ///  font-style: italic;
        ///  font-weight: 300;
        ///  src: local(&apos;Open Sans Light Italic&apos;), local(&apos;OpenSans-LightItalic&apos;), url(../fon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fonts {
            get {
                return ResourceManager.GetString("fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///@Include(@Model.Extension.RazorTemplate)
        ///
        ///&lt;footer id=&quot;main-footer&quot;&gt;
        ///    Extension: @Model.Extension.Name. &lt;a href=&quot;https://multiplug.app&quot; target=&quot;_blank&quot;&gt;MultiPlug .Net Edge Computing Platform&lt;/a&gt; Copyright © 2020 British Systems, all rights reserved.
        ///    &lt;a href=&quot;#&quot; class=&quot;pull-right&quot; id=&quot;on-top-link&quot;&gt;
        ///        On Top&amp;nbsp;&lt;i class=&quot; icon-chevron-up&quot;&gt;&lt;/i&gt;
        ///    &lt;/a&gt;
        ///&lt;/footer&gt;
        ///.
        /// </summary>
        internal static string FrameApp {
            get {
                return ResourceManager.GetString("FrameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///@Include(@Model.Extension.RazorTemplate)
        ///
        ///&lt;footer id=&quot;main-footer&quot;&gt;
        ///    Extension: @Model.Extension.Name. &lt;a href=&quot;https://multiplug.app&quot; target=&quot;_blank&quot;&gt;MultiPlug .Net Edge Computing Platform&lt;/a&gt; Copyright © 2020 British Systems, all rights reserved.
        ///    &lt;a href=&quot;#&quot; class=&quot;pull-right&quot; id=&quot;on-top-link&quot;&gt;
        ///        On Top&amp;nbsp;&lt;i class=&quot; icon-chevron-up&quot;&gt;&lt;/i&gt;
        ///    &lt;/a&gt;
        ///&lt;/footer&gt;.
        /// </summary>
        internal static string FrameExtension {
            get {
                return ResourceManager.GetString("FrameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using MultiPlug.Base.Http
        ///@model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;div class=&quot;extensions-heading&quot;&gt;
        ///    &lt;h2&gt;Apps&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;box&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot; style=&quot;margin-bottom: 20px&quot;&gt;
        ///
        ///        @foreach (var Extension in @Model.MultiPlugAPI.Extensions)
        ///        {
        ///            foreach (var HttpEndpoint in Extension.HttpEndpoints)
        ///            {
        ///                if (HttpEndpoint.isHidden || (HttpEndpoint.Type != HttpEndpointType.App))
        ///                {
        ///                    continue;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeApps {
            get {
                return ResourceManager.GetString("HomeApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;style&gt;
        ///    .extensions-heading img,
        ///    .extensions-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .extensions-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .extensions-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;extensions-heading&quot;&gt;
        ///    &lt;img height=&quot;35&quot; width=&quot;35&quot; alt=&quot;MultiPlug Icon&quot; src=&quot;assets/default2016/images/MultiPlug-Icon.png&quot;&gt;
        ///    &lt;h2&gt;Extens [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeExtensions {
            get {
                return ResourceManager.GetString("HomeExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///      display:inline-block;
        ///      vertical-align:middle;
        ///    }
        ///    .setting-heading img {
        ///    opacity: 0.7; filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///    margin-left:0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Settings Overview&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form class=&quot;&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeSettings {
            get {
                return ResourceManager.GetString("HomeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Internal Server Error - Multiplug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Internal Server Error&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.6.4 http://jquery.com/ | http://jquery.org/license */
        ///(function(a,b){function cu(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cr(a){if(!cg[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ch||(ch=c.createElement(&quot;iframe&quot;),ch.frameBorder=ch.width=ch.height=0),b.appendChild(ch);if(!ci||!ch.createElement)ci=(ch.contentWindow||ch.contentDocument).document,ci.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_6_4_min {
            get {
                return ResourceManager.GetString("jquery_1_6_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(n,t,i){function w(t,i){var u,f;if(n.isArray(t)){for(u=t.length-1;u&gt;=0;u--)f=t[u],n.type(f)===&quot;string&quot;&amp;&amp;r.transports[f]||(i.log(&quot;Invalid transport: &quot;+f+&quot;, removing it from the transports list.&quot;),t.splice(u,1));t.length===0&amp;&amp;(i.log(&quot;No transports remain within the specified transport array.&quot;),t=null)}else if(r.transports[t]||t===&quot;auto&quot;){if(t===&quot;auto&quot;&amp;&amp;r._.ieVersion&lt;=8)return[&quot;longPolling&quot;]}else i.log(&quot;Invalid transport: &quot;+t.toString()+&quot;.&quot;),t=null;return t}function b(n){return n===&quot;http:&quot;?80:n===&quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_signalR_2_2_0_min {
            get {
                return ResourceManager.GetString("jquery_signalR_2_2_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jsTree - v3.3.3 - 2016-10-31 - (MIT) */
        ///!function(a){&quot;use strict&quot;;&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):&quot;undefined&quot;!=typeof module&amp;&amp;module.exports?module.exports=a(require(&quot;jquery&quot;)):a(jQuery)}(function(a,b){&quot;use strict&quot;;if(!a.jstree){var c=0,d=!1,e=!1,f=!1,g=[],h=a(&quot;script:last&quot;).attr(&quot;src&quot;),i=window.document;a.jstree={version:&quot;3.3.3&quot;,defaults:{plugins:[]},plugins:{},path:h&amp;&amp;-1!==h.indexOf(&quot;/&quot;)?h.replace(/\/[^\/]+$/,&quot;&quot;):&quot;&quot;,idregex:/[\\:&amp;!^|()\[\]&lt;&gt;@*&apos;+~#&quot;;.,=\- \/${}%?`]/g,root:&quot;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_min {
            get {
                return ResourceManager.GetString("jstree_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-node,.jstree-children,.jstree-container-ul{display:block;margin:0;padding:0;list-style-type:none;list-style-image:none}.jstree-node{white-space:nowrap}.jstree-anchor{display:inline-block;color:#000;white-space:nowrap;padding:0 4px 0 1px;margin:0;vertical-align:top}.jstree-anchor:focus{outline:0}.jstree-anchor,.jstree-anchor:link,.jstree-anchor:visited,.jstree-anchor:hover,.jstree-anchor:active{text-decoration:none;color:inherit}.jstree-icon{display:inline-block;text-decoration:none;margin:0;padding: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jstree_style_min {
            get {
                return ResourceManager.GetString("jstree_style_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzBWV49_lSm1NYrwo_zkhivY {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzBWV49_lSm1NYrwo_zkhivY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzD0LW_43aMEzIO6XUTLjad8 {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzD0LW_43aMEzIO6XUTLjad8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzJX5f_9o1vgP2EXwfjgl7AY {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzJX5f_9o1vgP2EXwfjgl7AY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzK_j2U0lmluP9RWlSytm3ho {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzK_j2U0lmluP9RWlSytm3ho", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzKaRobkAwv3vxw3jMhVENGA {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzKaRobkAwv3vxw3jMhVENGA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzOgdm0LZdjqr5_oayXSOefg {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzOgdm0LZdjqr5_oayXSOefg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] k3k702ZOKiLJc3WVjuplzP8zf_FOSsgRmwsS7Aa9k2w {
            get {
                object obj = ResourceManager.GetObject("k3k702ZOKiLJc3WVjuplzP8zf_FOSsgRmwsS7Aa9k2w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@using MultiPlug.Base.Http
        ///@{
        ///    string AppsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.Location.Apps) ? &quot;active&quot; : &quot;&quot;; ;
        ///    string ExtensionsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.Location.Extensions) ? &quot;active&quot; : &quot;&quot;;
        ///    string SettingsActive = (Model.Context.Paths.Location == MultiPlug.Base.Http.Location.Settings) ? &quot;active&quot; : &quot;&quot;;
        ///
        ///    string Title = string.Empty;
        ///
        ///
        ///
        ///    switch (Model.Context.Paths.Location)
        ///    { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_menu_bg {
            get {
                object obj = ResourceManager.GetObject("left_menu_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Modernizr 2.6.2 (Custom Build) | MIT &amp; BSD
        /// * Build: http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inline [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modernizr_2_6_2_js {
            get {
                return ResourceManager.GetString("modernizr_2_6_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNShWV49_lSm1NYrwo_zkhivY {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNShWV49_lSm1NYrwo_zkhivY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSj0LW_43aMEzIO6XUTLjad8 {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSj0LW_43aMEzIO6XUTLjad8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSpX5f_9o1vgP2EXwfjgl7AY {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSpX5f_9o1vgP2EXwfjgl7AY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSq_j2U0lmluP9RWlSytm3ho {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSq_j2U0lmluP9RWlSytm3ho", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSqaRobkAwv3vxw3jMhVENGA {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSqaRobkAwv3vxw3jMhVENGA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5_oayXSOefg {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5_oayXSOefg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTP_ySUJH_bn48VBG8sNSv8zf_FOSsgRmwsS7Aa9k2w {
            get {
                object obj = ResourceManager.GetObject("MTP_ySUJH_bn48VBG8sNSv8zf_FOSsgRmwsS7Aa9k2w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug {
            get {
                object obj = ResourceManager.GetObject("MultiPlug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Icon {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Login {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function PopulateEventsData(mpevent) {
        ///
        ///    optgroups = [];
        ///
        ///    $.ajax({
        ///        url: &apos;multiplug/events/&apos;,
        ///        type: &apos;GET&apos;,
        ///        error: function () {
        ///            callback();
        ///        },
        ///        success: function (res) {
        ///
        ///            $.each(res.extensions, function () {
        ///                var exname = this.name;
        ///                optgroups.push({
        ///                    name: exname
        ///                });
        ///                $.each(this.events, function () {
        ///                    mpeventids.push({
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multiplug_selectize {
            get {
                return ResourceManager.GetString("multiplug_selectize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiPlug_Small {
            get {
                object obj = ResourceManager.GetObject("MultiPlug_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug App Not Found&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundApp {
            get {
                return ResourceManager.GetString("NotFoundApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug Extension Not Found&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundExtension {
            get {
                return ResourceManager.GetString("NotFoundExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    &lt;title&gt;Multiplug&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Not Found&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///
        ///    &lt;link href=&quot;assets/default2016/styles/fonts.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;assets/default2016/styles/bootstrap.min.css&quot; media=&quot;all&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;bootstrap-css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;section class=&quot;container&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFoundGlobal {
            get {
                return ResourceManager.GetString("NotFoundGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;content:&quot;&quot;;line-height:0}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}.pages-messages .nav-stacked .badge{display:inline-block;margin-top:1px;font-size:11px}.pages-messages .well{border:none!important;padding:0}.pages-messages .box [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_min {
            get {
                return ResourceManager.GetString("pages_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxgalQocB___pDVGhF3uS2Ks {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxgalQocB___pDVGhF3uS2Ks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxgyhumQnPMBCoGYhRaNxyyY {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxgyhumQnPMBCoGYhRaNxyyY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxhgVThLs8Y7ETJzDCYFCSLE {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxhgVThLs8Y7ETJzDCYFCSLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxhUVAXEdVvYDDqrz3aeR0Yc {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxhUVAXEdVvYDDqrz3aeR0Yc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxi_vZmeiCMnoWNN9rHBYaTc {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxi_vZmeiCMnoWNN9rHBYaTc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxiFaMxiho_5XQnyRZzQsrZs {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxiFaMxiho_5XQnyRZzQsrZs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxko2lTMeWA_kmIyWrkNCwPc {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxko2lTMeWA_kmIyWrkNCwPc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxl2umOyRU7PgRiv8DXcgJjk {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxl2umOyRU7PgRiv8DXcgJjk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxlf4y_3s5bcYyyLIFUSWYUU {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxlf4y_3s5bcYyyLIFUSWYUU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxmgpAmOCqD37_tyH_8Ri5MM {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxmgpAmOCqD37_tyH_8Ri5MM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxmhQUTDJGru_0vvUpABgH8I {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxmhQUTDJGru_0vvUpABgH8I", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxnywqdtBbUHn3VPgzuFrCy8 {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxnywqdtBbUHn3VPgzuFrCy8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxolIZu_HDpmDIZMigmsroc4 {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxolIZu_HDpmDIZMigmsroc4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxp6iIh_FvlUHQwED9Yt5Kbw {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxp6iIh_FvlUHQwED9Yt5Kbw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxpiMaisvaUVUsYyVzOmndek {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxpiMaisvaUVUsYyVzOmndek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxqfJul7RR1X4poJgi27uS4w {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxqfJul7RR1X4poJgi27uS4w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxqvyPXdneeGd26m9EmFSSWg {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxqvyPXdneeGd26m9EmFSSWg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxrBAWGjcah5Ky0jbCgIwDB8 {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxrBAWGjcah5Ky0jbCgIwDB8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxsPNMTLbnS9uQzHQlYieHUU {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxsPNMTLbnS9uQzHQlYieHUU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxujkDdvhIIFj_YMdgqpnSB0 {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxujkDdvhIIFj_YMdgqpnSB0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRmiXeptR36kaC0GEAetxv14vlcfyPYlAcQy2UfDRm4 {
            get {
                object obj = ResourceManager.GetObject("PRmiXeptR36kaC0GEAetxv14vlcfyPYlAcQy2UfDRm4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RjgO7rYTmqiVp7vzi_Q5URJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("RjgO7rYTmqiVp7vzi_Q5URJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! Select2 4.0.3 | https://github.com/select2/select2/blob/master/LICENSE.md */!function(a){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],a):a(&quot;object&quot;==typeof exports?require(&quot;jquery&quot;):jQuery)}(function(a){var b=function(){if(a&amp;&amp;a.fn&amp;&amp;a.fn.select2&amp;&amp;a.fn.select2.amd)var b=a.fn.select2.amd;var b;return function(){if(!b||!b.requirejs){b?c=b:b={};var a,c,d;!function(b){function e(a,b){return u.call(a,b)}function f(a,b){var c,d,e,f,g,h,i,j,k,l,m,n=b&amp;&amp;b.split(&quot;/&quot;),o=s.map,p=o&amp;&amp;o[&quot;*&quot;]||{};if(a&amp;&amp;&quot;.&quot;===a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string select2_min {
            get {
                return ResourceManager.GetString("select2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .select2-container{box-sizing:border-box;display:inline-block;margin:0;position:relative;vertical-align:middle}.select2-container .select2-selection--single{box-sizing:border-box;cursor:pointer;display:block;height:28px;user-select:none;-webkit-user-select:none}.select2-container .select2-selection--single .select2-selection__rendered{display:block;padding-left:8px;padding-right:20px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.select2-container .select2-selection--single .select2-selection__c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string select2_min1 {
            get {
                return ResourceManager.GetString("select2_min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * selectize.default.css (v0.12.4) - Default Theme
        /// * Copyright (c) 2013–2015 Brian Reavis &amp; contributors
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this
        /// * file except in compliance with the License. You may obtain a copy of the License at:
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software distributed under
        /// * the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectize_default {
            get {
                return ResourceManager.GetString("selectize_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! selectize.js - v0.12.4 | https://github.com/selectize/selectize.js | Apache License (v2) */
        ///!function(a,b){&quot;function&quot;==typeof define&amp;&amp;define.amd?define(&quot;sifter&quot;,b):&quot;object&quot;==typeof exports?module.exports=b():a.Sifter=b()}(this,function(){var a=function(a,b){this.items=a,this.settings=b||{diacritics:!0}};a.prototype.tokenize=function(a){if(a=e(String(a||&quot;&quot;).toLowerCase()),!a||!a.length)return[];var b,c,d,g,i=[],j=a.split(/ +/);for(b=0,c=j.length;b&lt;c;b++){if(d=f(j[b]),this.settings.diacritics)for(g in h) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selectize_min {
            get {
                return ResourceManager.GetString("selectize_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///      display:inline-block;
        ///      vertical-align:middle;
        ///    }
        ///    .setting-heading img {
        ///    opacity: 0.7; filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///    margin-left:0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Add Extensions&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form class=&quot;&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsAdd {
            get {
                return ResourceManager.GetString("SettingsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Apps&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsApps {
            get {
                return ResourceManager.GetString("SettingsApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Environment&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsEnvironment {
            get {
                return ResourceManager.GetString("SettingsEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Extensions&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf-8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsExtensions {
            get {
                return ResourceManager.GetString("SettingsExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Hosting&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf-8&quot; e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHosting {
            get {
                return ResourceManager.GetString("SettingsHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Housekeeping&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;h3 class=&quot;box-header&quot;&gt;
        ///    Storage        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHousekeeping {
            get {
                return ResourceManager.GetString("SettingsHousekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;div&gt;
        ///    &lt;img height=&quot;35&quot; width=&quot;35&quot; alt=&quot;MultiPlug Icon&quot; src=&quot;assets/default2016/images/MultiPlug-Icon.png&quot;&gt;
        ///    &lt;h2&gt;Housekeeping&lt;/h2&gt;
        ///&lt;/div&gt;
        ///
        ///
        ///&lt;div id=&quot;jstree&quot;&gt;
        ///    &lt;ul&gt;
        ///        @foreach (var FileDomain in @Model.Extension.Model.FileStatues)
        ///        {
        ///            &lt;li&gt;
        ///                Domain A @*@Extension.Name*@
        ///                &lt;ul&gt;
        ///                    @foreach (var FileListing in FileDomain)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHousekeepingStorage {
            get {
                return ResourceManager.GetString("SettingsHousekeepingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Performance&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsPerformance {
            get {
                return ResourceManager.GetString("SettingsPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Recipes&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf-8&quot; e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsRecipes {
            get {
                return ResourceManager.GetString("SettingsRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}.
        /// </summary>
        internal static string SettingsSecurity {
            get {
                return ResourceManager.GetString("SettingsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///        display: inline-block;
        ///        vertical-align: middle;
        ///    }
        ///
        ///    .setting-heading img {
        ///        opacity: 0.7;
        ///        filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///        margin-left: 0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Environment&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form method=&quot;post&quot; accept-charset=&quot;utf- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsSystem {
            get {
                return ResourceManager.GetString("SettingsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@{
        ///    Layout = &quot;MultiPlug.Ext.Thm.Default2016.Layout&quot;;
        ///}
        ///
        ///&lt;style&gt;
        ///    .setting-heading img,
        ///    .setting-heading h2 {
        ///      display:inline-block;
        ///      vertical-align:middle;
        ///    }
        ///    .setting-heading img {
        ///    opacity: 0.7; filter: alpha(opacity=70);
        ///    }
        ///
        ///    .setting-heading h2 {
        ///    margin-left:0.1em;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;div class=&quot;setting-heading&quot;&gt;
        ///    &lt;h2&gt;Update MultiPlug&lt;/h2&gt;
        ///&lt;/div&gt;
        ///&lt;form class=&quot;&quot; action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsUpdate {
            get {
                return ResourceManager.GetString("SettingsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] u_WUoqrET9fUeobQW7jkRRJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("u_WUoqrET9fUeobQW7jkRRJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBiYE0_AqJ3nfInTTiDXDjU4 {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBiYE0_AqJ3nfInTTiDXDjU4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBjTOQ_MqJVwkKsUn0wKzc2I {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBjTOQ_MqJVwkKsUn0wKzc2I", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBjUj_cnvWIuuBMVgbX098Mw {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBjUj_cnvWIuuBMVgbX098Mw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBkbcKLIaa1LC45dFaAfauRA {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBkbcKLIaa1LC45dFaAfauRA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBmo_sUJ8uO4YLWRInS22T3Y {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBmo_sUJ8uO4YLWRInS22T3Y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4 {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xjAJXh38I15wypJXxuGMBr6up8jxqWt8HVA3mDhkV_0 {
            get {
                object obj = ResourceManager.GetObject("xjAJXh38I15wypJXxuGMBr6up8jxqWt8HVA3mDhkV_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc {
            get {
                object obj = ResourceManager.GetObject("xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
